# Generated by Django 6.0.4 on 2026-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_category_product_old_price_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Party', 'Party'), ('Gym', 'Gym'), ('New Arrivals', 'New Arrivals'), ('Top Selling', 'Top Selling'), ('General', 'General')], default='General', max_length=100),
        ),
    ]
